language: python
python:
  - "3.6"      # current default Python on Travis CI
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r requirements_docs.txt

# command to run tests
script:
  - pytest

#after_success:
#  - cd docs && sphinx-apidoc -o source/ ../pyca && make html
#
#deploy:
#  provider: pages
#  skip-cleanup: true
#  keep-history: true
#  on:
#    branch: master
#  github-token: $GITHUB_TOKEN
#  local-dir: docs/_build/html
#  committer-from-gh: true